### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by macasas** [escamoteur/watch_it#12]
Hello Thomas

I have my own openweather api key, when I run the full url in a browser it functions and returns the json, but when I run it in your example app I just get errors.

```
flutter: TimeoutException after 0:00:05.000000: Future not completed - for param: null
flutter: Connection failed - for param: l
flutter: TimeoutException after 0:00:05.000000: Future not completed - for param: london

```
This normally fires the registeredHandler in HomePageState, unless I comment the handler out so I get it in the console as above.

```
class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    registerHandler(
        select: (WeatherManager x) => x.updateWeatherCommand.thrownExceptions,
        handler: (context, error, cancel) {
          showDialog(
              context: context,
              builder: (context) => AlertDialog(
                    title: const Text('An error has occurred!'),
                    content: Text(error.toString()),
                  ));
        });
```

Is there something else I need to personalise to make this example work?  I cannot find anything else?

Thanks
Dave

Also, Discord link gives Expired Invite error message.

**Comment by escamoteur** [comment]
Hmm, that is pretty weird, could you check with the dev tools network monitor what's really happens?
Dies it make the request at all?
Am 9. Sept. 2023, 19:06 +0200 schrieb Dave ***@***.***>:

**Comment by macasas** [comment]
Hi, yes it is making the network call, and then almost instantly coming back after 71 milliseconds and saying Error





Same URL in the browser

**Comment by escamoteur** [comment]
You are just using the example project and only added your api code?
Am 10. Sept. 2023, 16:06 +0200 schrieb Dave ***@***.***>:
> Hi, yes it is making the network call, and then almost instantly coming back after 71 milliseconds and saying Error
>
>
>
>
>
> Same URL in the browser
>
>
>
>
>
>
>
>

**Comment by macasas** [comment]
Yes, it did this from the start

Since then I have just been moving files around to try to mimic RVMS, duplicated the switch to play with commands, but nothing has changed the functionality.

**Comment by escamoteur** [comment]
I just tried the original myself and only if I have 'break on uncaught exceptions' enabled I get first a lookup exception reported in VS code (wich is currently a Bug 8n Flutter) and that leads to a timeout error displayed in an dialog.

Could you please try the original example if that works?
If yes, please share your current project with me
Am 10. Sept. 2023, 16:15 +0200 schrieb Dave ***@***.***>:
> Yes, it did this from the start
>
> Since then I have just been moving files around to try to mimic RVMS, duplicated the switch to play with commands, but nothing has changed the functionality.
>
>
>
>

**Comment by macasas** [comment]
Hi

Cloned your repo into clean, fresh folder
Opened project in vscode at root, watch_it
Selected watch_it pubspec.yaml and saved to get dependencies
Opened terminal, cd into example
Replaced appid with my own api key
Selected example pubspec.yaml and saved to get dependencies

Typed flutter run in vscode integrated terminal, opens in macos and immediately gives the error
A Dart VM Service on macOS is available at: http://127.0.0.1:57647/XK6pcEB7TLA=/
flutter: Connection failed - for param: null
Dialog appears in app
Network debugger shows request sent, failed in 25.0ms and just says Error
Closed it down

Tried in Terminal, same thing
Tried Run and Debug from vscode with no breakpoints ticked, same error

I’m running on osx 12.6 M1 chip, latest vscode, not sure what else to tell you.

**Comment by escamoteur** [comment]
Did the cleanly cloned version without your api key work?
Am 11. Sept. 2023, 10:14 +0200 schrieb Dave ***@***.***>:
> Hi
>
> Cloned your repo into clean, fresh folder
> Opened project in vscode at root, watch_it
> Selected watch_it pubspec.yaml and saved to get dependencies
> Opened terminal, cd into example
> Replaced appid with my own api key
> Selected example pubspec.yaml and saved to get dependencies
>
> Typed flutter run in vscode integrated terminal, opens in macos and immediately gives the error
> A Dart VM Service on macOS is available at: http://127.0.0.1:57647/XK6pcEB7TLA=/
> flutter: Connection failed - for param: null
> Dialog appears in app
> Network debugger shows request sent, failed in 25.0ms and just says Error
> Closed it down
>
> Tried in Terminal, same thing
> Tried Run and Debug from vscode with no breakpoints ticked, same error
>
> I’m running on osx 12.6 M1 chip, latest vscode, not sure what else to tell you.
>
>

**Comment by macasas** [comment]
Ran same 3 scenarios with your api key from original repo, and all give the same error.

**Comment by macasas** [comment]
and i get the same json response in a browser with the 2 api keys

**Comment by escamoteur** [comment]
Interesting, I have to try to run on Mac, you compiled for Mac Desktop App?
Are you on the latest Flutter stable?
Am 11. Sept. 2023, 10:22 +0200 schrieb Dave ***@***.***>:
> Ran same 3 scenarios with your api key from original repo, and all give the same error.
>
>
>

**Comment by macasas** [comment]
MBP14:example dave$ flutter --version
Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (3 months ago) • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1

MBP14:example dave$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 12.6 21G115 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.80.1)
[✓] VS Code
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

**Comment by escamoteur** [comment]
Latest stable is 3.13.2 please try it with that too.
I will look into it later today, have to doy normal job first
Am 11. Sept. 2023, 10:28 +0200 schrieb Dave ***@***.***>:
>
>
> MBP14:example dave$ flutter --version
> Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 796c8ef792 (3 months ago) • 2023-06-13 15:51:02 -0700
> Engine • revision 45f6e00911
> Tools • Dart 3.0.5 • DevTools 2.23.1
>
> MBP14:example dave$ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.10.5, on macOS 12.6 21G115 darwin-arm64, locale en-GB)
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 14.2)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2021.3)
> [✓] VS Code (version 1.80.1)
> [✓] VS Code
> [✓] Connected device (2 available)
> [✓] Network resources
>
> • No issues found!
>
>
>
>

**Comment by macasas** [comment]
Sorry, yes on a macOS desktop.

I will try it on Android and see if there are any differences

Also, do you have any watch_it examples where a list of items is being selected, and those selections are creating another list in the model, like selecting favourites..

**Comment by escamoteur** [comment]
If you can create a project with a mock data model for such an app, I can add the watch_it part😊
Am 11. Sept. 2023, 10:30 +0200 schrieb Dave ***@***.***>:
> Sorry, yes on a macOS desktop.
>
> I will try it on Android and see if there are any differences
>
> Also, do you have any watch_it examples where a list of items is being selected, and those selections are creating another list in the model, like selecting favourites..
>
>
>

**Comment by macasas** [comment]
Okay, runs fine in iOS simulator :-)

I will update

**Comment by macasas** [comment]
Here is the macOS answer.

https://stackoverflow.com/questions/57841871/flutter-http-get-fails-on-macos-build-target-connection-failed

With the relevant part here

You need to add:

<key>com.apple.security.network.client</key>
<true/>
to macos/Runner/DebugProfile.entitlements and macos/Runner/Release.entitlements.

This is documented here <https://docs.flutter.dev/development/platform-integration/macos/building#setting-up-entitlements> and here <https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_network_client>.

And now the project is running on macOS :-)

**Comment by escamoteur** [comment]
Thanks for letting me know. I was already thinking it could be a permission problem
Am 11. Sept. 2023, 10:59 +0200 schrieb Dave ***@***.***>:
> Here is the macOS answer.
>
> https://stackoverflow.com/questions/57841871/flutter-http-get-fails-on-macos-build-target-connection-failed
>
> With the relevant part here
>
> You need to add:
>
> <key>com.apple.security.network.client</key>
> <true/>
> to macos/Runner/DebugProfile.entitlements and macos/Runner/Release.entitlements.
>
> This is documented here <https://docs.flutter.dev/development/platform-integration/macos/building#setting-up-entitlements> and here <https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_network_client>.
>
> And now the project is running on macOS :-)
>
>
>
>

**Comment by esDotDev** [comment]
Should we close this? This is a very common issue when creating macOS apps, and nothing to do with WatchIt.
