### ISSUE TITLE
Readme Typo in section: `ValueListenables / ValueNotifiers`

### ISSUE THREAD

**Issue by florentmsl** [escamoteur/watch_it#17]
First things first, this is an awesome package! Thank you very much.

I found a little typo in the docs in the section `ValueListenables / ValueNotifiers`:

```dart
class UserManager
{
  final userName = ChangeNotifier<String>();
}
```

and this does not compile, it probably should be something like:

```dart
class UserManager
{
  final userName = ValueNotifier<String>('James');
}
```

**Comment by escamoteur** [comment]
Good catch
Am 30. Okt. 2023, 19:00 +0100 schrieb florentmx ***@***.***>:
