### ISSUE TITLE
Use with BottomNavigationBar

### ISSUE THREAD

**Issue by Osmosis311** [escamoteur/watch_it#2]
Hi Thomas!

First off, thanks so much for this amazing library.  It works really well so far and I love the simplicity.

Quick question: is there a trick to using this with a BottomNavigationBar?  I tried instantiating a widget in an array of pages for hot-swapping as the body of my main page when the navigation bar selection changes, but I'm getting this error:

`watchIt can only be called inside a build function`

Thanks!

**Comment by Osmosis311** [comment]
Figured it out :-)

**Comment by escamoteur** [comment]
What was the problem?

Thomas
Am 20. Juni 2023, 03:38 +0200 schrieb Danny Ackerman ***@***.***>:
