### ISSUE TITLE
watchValue from service1 in a service2

### ISSUE THREAD

**Issue by matthewkooshad** [escamoteur/watch_it#20]
i've just began trying out watch_it; thanks!

how could i use watchValue from service1 in a service2? so far, i'm trying it in widgets that extend WatchingWidget. i have some situations of shared state, where widgets are doing a lookup in service2, but the state is coming from service1. i like the separation i have, and i would ideally in this situation not watch the value from service1 and pass it from the widget into service2.

**Comment by escamoteur** [comment]
Hi, watch_it's watch functions can only be used inside the build function of either WatchingWidgets or widgets that use the WatchItMixin.
I don't really understand why you would need watch_it to react on a change of a ValueNotifier in another service? You can simply either use the registerHandler function of it or use my functional_listener package which adds a `listen()` extension method go ValueListeneables/ValueNotifiers

**Comment by matthewkooshad** [comment]
For the situation I've asked this about for, the widget is calling service2, which is needing to know about dark mode setting. The dark mode setting state is in service1. I need service2 to know the dark mode setting to give the widget the correct color, but I would like for the widget to be agnostic about the dark mode, and simply receive the color from service2. This requires service2 to provide a fresh color value to the widget when dark mode value changes. 

I'll take a look at functional_listener. Does what I described just now make more sense? Thank you

**Comment by escamoteur** [comment]
sure, as said, you don't need functional listeners, you can just use 
https://api.flutter.dev/flutter/foundation/ChangeNotifier/addListener.html
to make one service react to a state change inside another service. 
I personally like the syntax of 'listen# from functional listener more
