### ISSUE TITLE
watch error: Couldn't infer type parameter 'T'.

### ISSUE THREAD

**Issue by matthewkooshad** [escamoteur/watch_it#21]
the `watch` example from the docs isn't working for me:
`final userName = watch(di<UserModel>()).name;`

i'm trying similarly to that line in the build method of my widget:
`final screenTitle = watch(di<RootItemsScheme>()).screenTitle;`

> Couldn't infer type parameter 'T'.
> 
> Tried to infer 'RootItemsScheme' for 'T' which doesn't work:
>   Type parameter 'T' is declared to extend 'Listenable' producing 'Listenable'.
> The type 'RootItemsScheme' was inferred from:
>   Parameter 'target' declared as     'T'
>                      but argument is 'RootItemsScheme'.
> 
> Consider passing explicit type argument(s) to the generic.

from main:
`final gi = GetIt.instance;`
`gi.registerSingleton<RootItemsScheme>(RootItemsScheme());`

more info on screenTitle:
` String get screenTitle {`
`    switch (_itemType.value) {`
...

`_itemType` is a `ValueListenable` in `RootItemsScheme` class, from which, i'm trying to return a string based on the value of it at the time i use the `screenTitle` getter.

**Comment by matthewkooshad** [comment]
i'm thinking the problem is that i'm trying to watch a string value rather than a notifier. i don't need a setter in this situation, it's only a getter logic that i need, and it's based on a ValueListenable, as noted. i was thinking i need the watch in order to see the latest value from the service, even though the service is producing a value based on the ValueListenable. please advise, thanks.

**Comment by matthewkooshad** [comment]
referencing that string getter that has logic based on a ValueListenable is not triggering a rebuild whenever the value changes of that the ValueListenable would be reflecting. the ValueListenable is reflecting a value from a ValueNotifier and that part is working fine. but, it's the logical string result that i'm needing reflected in the widget as the logic would produce a different value, is the part that i need to resolve.

**Comment by escamoteur** [comment]
Does UserModel implement tge Listenable interface? For instance by extending a ChangeNotifier?
Am 13. Dez. 2023, 03:48 +0100 schrieb Matthew Kooshad ***@***.***>:

**Comment by matthewkooshad** [comment]
No. I didn't see that in the documentation noted. I'll look into doing
that. Thanks

**Comment by escamoteur** [comment]
You can only watch an object that implements listenable otherwise watch_it wouldn't know that the object has changed.
Am 13. Dez. 2023, 14:27 +0100 schrieb Matthew Kooshad ***@***.***>:
> No. I didn't see that in the documentation noted. I'll look into doing
> that. Thanks
>

**Comment by matthewkooshad** [comment]
i just saw in the docs where i missed the `extends ChangeNotifier` for my class. thanks, and sorry that i missed that.

**Comment by matthewkooshad** [comment]
notice one example in your docs that doesn't have the `extends ChangeNotifier`. please confirm if that's for when just using watchValue as i was already trying. 
```
class Model {
    final country = ValueNotifier<String>('Canada');
    ...
}
di.registerSingleton<Model>(Model());
```

**Comment by escamoteur** [comment]
In that case we can only watch the "country" property because it's a ValueNotifier which implements Listenable
Am 15. Dez. 2023, 01:37 +0100 schrieb Matthew Kooshad ***@***.***>:
