### ISSUE TITLE
Document WatchingStatefulWidget and WatchingStatefulWidgetMixin

### ISSUE THREAD

**Issue by exaby73** [escamoteur/watch_it#24]
I noticed in the docs that there is no use of `StatefulWidgets`, which makes sense. So without access to `initState`, how do I run code only once on first build?

More broadly, are there any plans to support lifecycle hooks, like `initState`, `dispose`, etc.?

Side note: I usually use `flutter_hooks` for this, with an empty dependency array passed to `useEffect` but seems `watch_it` is not compatible with `HookWidget`

Edit: I see that there are widgets and mixins for `StatefulWidget` as well. Maybe this should be documented. While this solves my issue, I think I'll keep this issue open for discussion on docs. Thanks

**Comment by escamoteur** [comment]
Indeed, there is a mixin for StatefulWidgets and a WatchingStatefulWidget see https://github.com/escamoteur/watch_it#the-watchingwidgets but I agree that I could add a sentence of using the WatchItStatefulWidget

**Comment by escamoteur** [comment]
Btw I'm thinking ob adding an `executeOnce` function

**Comment by exaby73** [comment]
`executeOnce` would be really good. It would help with eliminating the need for `StatefulWidget`s altogether

**Comment by matthewkooshad** [comment]
after looking at the document, i'm needing help still with how i would make `class MyApp extends WatchingStatefulWidget {`. what would below look like to be able to use watchValue in _MyAppState ?

```
class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late AppLinks _appLinks;
  StreamSubscription<Uri>? _linkSubscription;

  @override
  void initState() {
    super.initState();

    _initDeepLinks();
  }

  @override
  void dispose() {
    _linkSubscription?.cancel();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
   //needing to use watchValue
  }
}
```
