### ISSUE TITLE
Exception When Registering Singleton in Flutter Web

### ISSUE THREAD

**Issue by cliftonlabrum** [escamoteur/watch_it#34]
I've been successfully using watch_it for a while now in an app that runs on Windows, Mac, iOS, and Android. I've set out to make my app work on **web**, and I keep getting stuck with an exception anytime I use `watchPropertyValue`.

Here's an example:

```dart
//Registered in main.dart
di.registerSingleton<ModelFilter>(ModelFilter());
```
My `ModelFilter` file is a singleton that is set up like this:
```dart
class ModelFilter with ChangeNotifier {
  static ModelFilter get to => di<ModelFilter>();

  //Dates
  String _filterDate = 'All';
  String get filterDate => _filterDate;
  set filterDate(String value) {
    _filterDate = value;
    notifyListeners();
  }
}
```

Here is how I use it in a widget:
```dart
Widget build(BuildContext context) {
  watchPropertyValue((ModelFilter model) => model.filterDate);
  //...
}
```
Here's the exception I get:
```js
Error
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
packages/get_it/get_it_impl.dart 14:19                                            throwIfNot
packages/get_it/get_it_impl.dart 435:5                                            [_findFactoryByNameAndType]
packages/get_it/get_it_impl.dart 463:29                                           get
packages/get_it/get_it_impl.dart 554:12                                           call
packages/watch_it/src/watch_it.dart 161:47                                        watchPropertyValue
```
Is there something special I need to do to register my dependency on web? It works flawlessly in the native apps.

**Comment by escamoteur** [comment]
There was some other issue on the we related to get_it. I have to look it up, I think there was a workaround if it's a same. A minimal repro project would be helpful.
Am 25. Juni 2024, 03:17 +0100 schrieb Clifton Labrum ***@***.***>:

**Comment by escamoteur** [comment]
ok, this seems not to be related to the old web bug.
what sort of Error does it throw? you didn't mention that.
could you provide me with a very simple repro-project that shows this behaviour?

**Comment by cliftonlabrum** [comment]
I'm working on a reproduction project. But of course, the crash doesn't occur in the new project. I'm adding stuff in to see where it happens. I'll keep you posted. Thanks for your help! 😊

**Comment by escamoteur** [comment]
That's actually a good start, it might lead you to the real problem
Am 25. Juni 2024, 22:04 +0100 schrieb Clifton Labrum ***@***.***>:

**Comment by escamoteur** [comment]
What was the problem?
Am 16. Juli 2024, 17:50 +0100 schrieb Clifton Labrum ***@***.***>:

**Comment by cliftonlabrum** [comment]
@escamoteur I couldn't ever reproduce it in a sample app, though I still have the problem in my real app. I didn't want to leave this open since it's most likely a problem with my code.
