### ISSUE TITLE
Why is this package not included in the fluttercommunity repository?

### ISSUE THREAD

**Issue by xpwmaosldk** [escamoteur/watch_it#35]
I came across it being promoted in the get_it package, but it's a personal repository, which is confusing.

**Comment by escamoteur** [comment]
Hi,

I might move it to the Flutter community org in the near future but as I m the only maintainer of my packagesbfor most of the time I didn't see the need yet.
But good to know that it is important for users. So I will probably move it
Cheers
Thomas
Am 15. Juli 2024, 05:28 +0100 schrieb xpwmaosldk ***@***.***>:

**Comment by xpwmaosldk** [comment]
Thank you for the response.
If the repository is moved, I think there will be more contributors.
If it is moved and settled in the fluttercommunity, I would also like to try using it.
It's very intuitive and easy, which is great.
