### ISSUE TITLE
Possible crash when creating two simultaneous widgets that use pushScope

### ISSUE THREAD

**Issue by jefflongo** [escamoteur/watch_it#37]
watch_it's `pushScope` function creates a scope using the current microsecond since epoch as the name. If two widgets created as part of another widget both call `pushScope`, or if a widget that calls `pushScope` creates another widget that calls `pushScope` as part of its `build` method, the calls to `pushScope` are sometimes close enough that they land on the same microsecond causing `get_it` to fail an assertion that two scopes cannot have the same name.

Example:
```dart
class Widget1 extends StatelessWidget with WatchItMixin {
  @override
  Widget build(BuildContext context) {
    pushScope(
        init: (g) => g.registerSingleton<Widget1Logic>(Widget1Logic()), isFinal: true);
    
    return Widget2(...);
  }
}
```

```dart
class Widget2 extends StatelessWidget with WatchItMixin {
  @override
  Widget build(BuildContext context) {
    pushScope(
        init: (g) => g.registerSingleton<Widget2Logic>(Widget2Logic()), isFinal: true);
    
    return Container(...);
  }
}
```

Result:
```
You already have used the scope name AutoScope: 1725168012270932
'package:get_it/get_it_impl.dart':
Failed assertion: line 918 pos 7: 'scopeName == null ||
          _scopes.firstWhereOrNull((x) => x.name == scopeName) == null'
```

**Comment by escamoteur** [comment]
Oh, I didn't think that that would be possible. I will change it to use a uuid then.
Am 1. Sept. 2024, 06:15 +0100 schrieb Jeff ***@***.***>:

**Comment by jefflongo** [comment]
Why not just have a number generator that increments a counter at each call instead?

**Comment by escamoteur** [comment]
Actually you are right. That would also solve the problem.
Do you want to make a PR 😉
Am 1. Sept. 2024, 16:55 +0100 schrieb Jeff ***@***.***>:

**Comment by jefflongo** [comment]
Yes I will open a PR soon
