### ISSUE TITLE
Handling nullable streams with drift - what am I missing?

### ISSUE THREAD

**Issue by wrouesnel** [escamoteur/watch_it#39]
So I have a basic drift database and do something like this:

```
    final part =
        watchStream((PartController controller) => controller.part(partId).watchSingleOrNull(), initialValue: null);
```

`part` is then an AsyncValue.

What I'm not clear on is how I distinguish between two possible results here: that the stream returned a null value, but did return something, and whether I'm still waiting for an initial non-null value?

Basically when I need to:
```
part.hasData ? buildSomeWidget(part.data!) : CircularProgressIndicator()
```

i.e. I want to distinguish in the UI between "we are waiting for something to be returned from the database" versus "there's no value in the database".

This would presumably apply in other situations like sending an HTTP request. It does occur to me I could use a sentinel value in `initialValue` here, but that doesn't quite solve the problem since `hasData` only returns true for a non-null value.

What's the correct way to use AsyncValue to distinguish between getting data (which may be null) versus still waiting for data?

**Comment by escamoteur** [comment]
How would you express the same situation using a StreamBuilder?
Am 8. Okt. 2024, 02:44 +0100 schrieb Will Rouesnel ***@***.***>:

**Comment by wrouesnel** [comment]
Honestly no idea, a peruse of easy to use pointed me at this library. But looking at the code, it seems apparent that StreamBuilder wouldn't let this work either since null is just not considered a valid value.

So the solution is I need to make sure I map everything to a DTO object which can represent a possible null from the database - or not use watchSingleOrNull and instead look for the empty set which is a little bit uglier but probably less overhead for rapid prototyping it would seem.

**Comment by escamoteur** [comment]
I mean null would be OK if it is a value that your stream emits to signal a certain state. But if it doesn't emit that all you can't use it.
Am 8. Okt. 2024, 09:06 +0100 schrieb Will Rouesnel ***@***.***>:
