### ISSUE TITLE
Possible to automatically dispose when using registerFactory

### ISSUE THREAD

**Issue by KlausJokisuo** [escamoteur/watch_it#4]
Is it possible to automatically dispose a instance when it's no longer used anywhere? Similarly how Provider and flutter_bloc does?

Thanks 👍

**Comment by escamoteur** [comment]
I honestly wonder how these packages manage to know when an object ist used anymore.
If you can explain it to me how you would do it I m open for adding it.
You always can use pushScope to limit the live time of objects to that of a widget.

Thomas
Am 13. Juli 2023, 07:59 +0200 schrieb Klaus Jokisuo ***@***.***>:

**Comment by KlausJokisuo** [comment]
Actually, I don't think there is a need for such a feature after all. In edge cases, scopes will be sufficient. Thanks 👍
