### ISSUE TITLE
WatchingStatefulWidget: how to use?

### ISSUE THREAD

**Issue by matthewkooshad** [escamoteur/watch_it#40]
after looking at the readme (and also https://github.com/escamoteur/watch_it/issues/24), i'm needing help still with how i would make `class MyApp extends WatchingStatefulWidget {`. what would below look like to be able to use watchValue in _MyAppState ?

```
class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late AppLinks _appLinks;
  StreamSubscription<Uri>? _linkSubscription;

  @override
  void initState() {
    super.initState();

    _initDeepLinks();
  }

  @override
  void dispose() {
    _linkSubscription?.cancel();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
   //needing to use watchValue
  }
}
```
thank you,

**Comment by escamoteur** [comment]
just replace StatefulWidget with WatchingStatefulWidget, what is the problem?

**Comment by matthewkooshad** [comment]
thanks, i tried that, and it worked.

the confusion i had was that previously i used `class MyApp extends WatchingWidget` as a stateless widget was fine. but, i am now needing init and dispose for the applinks functionality i am working on to use now.

**Comment by matthewkooshad** [comment]
thanks, i tried that, and it worked.

the confusion i had was that previously i used `class MyApp extends WatchingWidget` as a stateless widget was fine. but, i am now needing init and dispose for the applinks functionality i am working on to use now.
