### ISSUE TITLE
Allow watching nullable streams

### ISSUE THREAD

**Issue by yangsfang** [escamoteur/watch_it#9]
A `Stream<int?>` can have valid successful value of `null` inside the stream. 

When using `watchStream` in `watch_it` and [`get_it_mixin`](https://pub.dev/packages/get_it_mixin), it will throw an error due to an assertion at https://github.com/escamoteur/watch_it/blob/617e8d29ef211cdc69f79594e83966b63228beeb/lib/src/watch_it_state.dart#L336. 

The expected behavior is for watch it to not throw this error, and to trigger a rebuild with a null value for this stream.

**Comment by escamoteur** [comment]
I think I fixed the same thing for the normal watch just recently
